version: '3'
services:
  proxy:
    image: meirafa/jenkins
    container_name: jenkinsCompose
    build:
      context: .
    ports:
      - "80:8080"
    networks:
      - webservereth
#nome da minha placa de rede do container
networks:
  webservereth:
    driver: bridge

#docker-compose up -d